<a href="https://colab.research.google.com/github/Bhavika2006481/workshop/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Numpy

In [65]:
import numpy as np

In [66]:
import numpy as np

# Creating Numpy Arrays

In [67]:
np.array
import numpy as np
a=np.array([1,2,3])
print(a)
a=np.array([1,2,3,4,5,6])
a

[1 2 3]


array([1, 2, 3, 4, 5, 6])

# 2D array: An array of arrays

In [68]:
#20 and 30
b=np.array([[2,3],[5,6]])
print(b)

[[2 3]
 [5 6]]


# 3D array : An array of 2D array

In [69]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [70]:
#dtype
#np.array([1,2,3],dtype=float)
a = np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [71]:
a=np.array([1,2,3],dtype=np.uint8)
print(a)
print(a.dtype)

b=np.array([1,2,3],dtype=complex)
print(b)
print(b.dtype)

[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [72]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [73]:
#with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [74]:
np.ones and np.zeros

<function numpy.zeros>

In [75]:
#np.random
np.random.random((3,4))

array([[0.04948186, 0.38316715, 0.52836768, 0.02398807],
       [0.26438964, 0.12817272, 0.9665471 , 0.65083754],
       [0.84540236, 0.79431819, 0.63792542, 0.05223005]])

In [76]:
#np.linspace
np.linspace(-10,10,1000,dtype=float)

array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
        -9.91991992,  -9.8998999 ,  -9.87987988,  -9.85985986,
        -9.83983984,  -9.81981982,  -9.7997998 ,  -9.77977978,
        -9.75975976,  -9.73973974,  -9.71971972,  -9.6996997 ,
        -9.67967968,  -9.65965966,  -9.63963964,  -9.61961962,
        -9.5995996 ,  -9.57957958,  -9.55955956,  -9.53953954,
        -9.51951952,  -9.4994995 ,  -9.47947948,  -9.45945946,
        -9.43943944,  -9.41941942,  -9.3993994 ,  -9.37937938,
        -9.35935936,  -9.33933934,  -9.31931932,  -9.2992993 ,
        -9.27927928,  -9.25925926,  -9.23923924,  -9.21921922,
        -9.1991992 ,  -9.17917918,  -9.15915916,  -9.13913914,
        -9.11911912,  -9.0990991 ,  -9.07907908,  -9.05905906,
        -9.03903904,  -9.01901902,  -8.998999  ,  -8.97897898,
        -8.95895896,  -8.93893894,  -8.91891892,  -8.8988989 ,
        -8.87887888,  -8.85885886,  -8.83883884,  -8.81881882,
        -8.7987988 ,  -8.77877878,  -8.75875876,  -8.73

In [77]:
np.random.randint(2,10,5)

array([5, 9, 9, 5, 3])

In [78]:
import numpy as np

In [79]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [80]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.ndim

[[1 2 3]
 [4 5 6]]


2

In [82]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [83]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.size

[[1 2 3]
 [4 5 6]]


6

In [84]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [85]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.itemsize

[[1 2 3]
 [4 5 6]]


8

In [86]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.nbytes

[[1 2 3]
 [4 5 6]]


48

In [87]:
a=np.arange(12)
a.ndim

1

In [88]:
#ndim
a3.ndim

3

In [89]:
a1.shape

(10,)

In [90]:
a2.shape

(3, 4)

In [91]:
a3.shape

(2, 2, 2)

# Changing Datatypes:
 You can change the data type of a Numpy array using the **.astype**()  method.

In [92]:
a3.dtype

dtype('int64')

In [93]:
#astype
a3.astype(np.int32)
a3.astype(np.float32).dtype

dtype('float32')

# Array operations

In [94]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
#scaler operations

#arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [96]:
#relational
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [97]:
#vector operations
#arithmetic
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [98]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[87., 58., 98.],
       [61., 18., 99.],
       [98., 31., 78.]])

In [99]:
#max/min/sum/np.prod
#0 ->col and 1 ->row
np.prod(a1,axis=0)

array([520086.,  32364., 756756.])

In [100]:
#mean/median/std/var
np.sin(a1)

array([[-0.82181784,  0.99287265, -0.57338187],
       [-0.96611777, -0.75098725, -0.99920683],
       [-0.57338187, -0.40403765,  0.51397846]])

In [101]:
#angle array in degrees
angles_deg=np.array([0,30,45,60,90])
#convert to radians
angles_rad=np.deg2rad(angles_deg)

print("angles in degrees:",angles_deg)
print("angles in radians:",angles_rad)

print("Sine:",np.sin(angles_rad))
print("Cosine:",np.cos(angles_rad))
print("Tangent:",np.tan(angles_rad))

angles in degrees: [ 0 30 45 60 90]
angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [102]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [103]:
#log and exponents
np.exp(a1)

array([[6.07603023e+37, 1.54553894e+25, 3.63797095e+42],
       [3.10429794e+26, 6.56599691e+07, 9.88903032e+42],
       [3.63797095e+42, 2.90488497e+13, 7.49841700e+33]])

In [104]:
#round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[68., 84.,  9.],
       [33., 15., 60.]])

# Indexing and Slicing

In [105]:


a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [106]:
a1

array([[87., 58., 98.],
       [61., 18., 99.],
       [98., 31., 78.]])

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a2[1,0]

np.int64(4)

In [109]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [110]:
a3[1,0]

np.int64(15)

In [111]:
a3[1,1]

np.int64(16)

In [112]:
a1

array([[87., 58., 98.],
       [61., 18., 99.],
       [98., 31., 78.]])

In [113]:
a1[2:5:2]

array([[98., 31., 78.]])

In [122]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [123]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [124]:
a2[1,::3]

array([4, 7])

In [125]:
a2[0,:]

array([0, 1, 2, 3])

In [126]:
a2[:,2]

array([ 2,  6, 10])

In [127]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [128]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [129]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [130]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [131]:
a3[0,1,:]

array([3, 4, 5])

# Iterating

In [114]:
a1

for i in a1:
  print(i)

[87. 58. 98.]
[61. 18. 99.]
[98. 31. 78.]


In [115]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [116]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [132]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [118]:
for i in a3:
  print(i)

[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]


In [119]:
for i in np.nditer(a3):
  print(i)

12
13
14
15
16
17
18
19
20
21
22
23


In [120]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [121]:
# ravel
a3.ravel()

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])